### ISSUE TITLE
Interoperability

### ISSUE THREAD

**Issue by ivantcholakov** [narfbg/SimpleEncryption#9]
Would it be possible the chosen algorithm to be ported to other languages?

For JavaScript (Node/io.js, for browsers it does not make sense) I know this library:
sjcl - https://github.com/bitwiseshiftleft/sjcl
The idea is with help of this library SimpleEncryption to be implemented for JavaScript and it to be compatible with the PHP implementation.

For other languages possibility for porting would be nice too. By the way the suggestion #2 seems to me good for this goal.

**Comment by narfbg** [comment]
Of course it can be ported ... almost any code can be ported to another language.
